<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>413aa574-faa6-45b6-ad06-7e15af823228</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <!-- API là composition root nên được phép reference Application và Infrastructure để đăng ký DI. -->
    <ProjectReference Include="../ProductHub.Application/ProductHub.Application.csproj" />
    <ProjectReference Include="../ProductHub.Infrastructure/ProductHub.Infrastructure.csproj" />
  </ItemGroup>

</Project>
