services:
  postgres:
    image: postgres:17-alpine
    container_name: producthub-postgres
    environment:
      POSTGRES_DB: producthub
      POSTGRES_USER: producthub
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - producthub_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U producthub -d producthub"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  producthub_postgres_data: